name: Generate SBOM

on:
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm install

      - name: Install CycloneDX module
        run: npm install --save-dev @cyclonedx/bom

      - name: Generate SBOM
        run: npx cyclonedx-bom -o sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
